const INIT_SEARCH = "INIT_SEARCH";
const SEARCH_SUCCESSFULL = "SEARCH_SUCCESSFULL";
const SEARCH_FAIL = "SEARCH_FAIL";
const CLEAR_SEARCH = "CLEAR_SEARCH";

export { INIT_SEARCH, SEARCH_SUCCESSFULL, SEARCH_FAIL, CLEAR_SEARCH };
