const ADD_CATEGORY = "ADD_CATEGORY";
const ADD_CATEGORY_SUCCESSFULL = "ADD_CATEGORY_SUCCESSFULL";
const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
const FETCH_CATEGORY = "FETCH_CATEGORY";
const FETCH_CATEGORY_SUCCESSFULL = "FETCH_CATEGORY_SUCCESSFULL";
const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const FETCH_CATEGORIES_SUCCESSFULL = "FETCH_CATEGORIES_SUCCESSFULL";
const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
const FETCH_ALL_PHOTOS = "FETCH_ALL_PHOTOS";
const FETCH_ALL_PHOTOS_SUCCESSFULL = "FETCH_ALL_PHOTOS_SUCCESSFULL";
const FETCH_ALL_PHOTOS_FAIL = "FETCH_ALL_PHOTOS_FAIL";
const UPLOAD_PHOTO = "UPLOAD_PHOTO";
const UPLOAD_PHOTO_SUCCESSFULL = "UPLOAD_PHOTO_SUCCESSFULL";
const UPLOAD_PHOTO_FAIL = "UPLOAD_PHOTO_FAIL";
const SELECT_PHOTO = "FETCH_PHOTO";
const SELECT_PHOTO_SUCCESSFULL = "FETCH_PHOTO_SUCCESSFULL";
const SELECT_PHOTO_FAIL = "FETCH_PHOTO_FAIL";
const UPDATE_PHOTO_RATING = "UPDATE_PHOTO_RATING";
const UPDATE_PHOTO_RATING_SUCCESSFULL = "UPDATE_PHOTO_RATING_SUCCESSFULL";
const UPDATE_PHOTO_RATING_FAIL = "UPDATE_PHOTO_RATING_FAIL";

export {
  ADD_CATEGORY,
  ADD_CATEGORY_SUCCESSFULL,
  ADD_CATEGORY_FAIL,
  FETCH_CATEGORY,
  FETCH_CATEGORY_SUCCESSFULL,
  FETCH_CATEGORY_FAIL,
  FETCH_CATEGORIES,
  FETCH_CATEGORIES_SUCCESSFULL,
  FETCH_CATEGORIES_FAIL,
  FETCH_ALL_PHOTOS,
  FETCH_ALL_PHOTOS_SUCCESSFULL,
  FETCH_ALL_PHOTOS_FAIL,
  UPLOAD_PHOTO,
  UPLOAD_PHOTO_SUCCESSFULL,
  UPLOAD_PHOTO_FAIL,
  SELECT_PHOTO,
  SELECT_PHOTO_SUCCESSFULL,
  SELECT_PHOTO_FAIL,
  UPDATE_PHOTO_RATING,
  UPDATE_PHOTO_RATING_SUCCESSFULL,
  UPDATE_PHOTO_RATING_FAIL,
};
