const LOGIN_USER = "LOGIN_USER";
const LOGIN_USER_SUCCESSFULL = "LOGIN_USER_SUCCESSFULL";
const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
const REGISTER_USER = "REGISTER_USER";
const REGISTER_USER_SUCCESSFULL = "REGISTER_USER_SUCCESSFULL";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
const FETCH_USER = "FETCH_USER";
const FETCH_USER_SUCCESSFULL = "FETCH_USER_SUCCESSFULL";
const FETCH_USER_FAIL = "FETCH_USER_FAIL";
const FETCH_USERS = "FETCH_USERS";
const FETCH_USERS_SUCCESSFULL = "FETCH_USERS_SUCCESSFULL";
const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export {
  LOGIN_USER,
  LOGIN_USER_SUCCESSFULL,
  LOGIN_USER_FAIL,
  REGISTER_USER,
  REGISTER_USER_SUCCESSFULL,
  REGISTER_USER_FAIL,
  FETCH_USER,
  FETCH_USER_SUCCESSFULL,
  FETCH_USER_FAIL,
  FETCH_USERS,
  FETCH_USERS_SUCCESSFULL,
  FETCH_USERS_FAIL,
};
