const OPEN_SIGN_FORM = "OPEN_SIGN_FORM";
const CLOSE_SIGN_FORM = "CLOSE_SIGN_FORM";
const OPEN_REGISTER_FORM = "OPEN_REGISTER_FORM";
const CLOSE_REGISTER_FORM = "CLOSE_REGISTER_FORM";
const OPEN_ADD_CATEGORY_FORM = "OPEN_ADD_CATEGORY_FORM";
const CLOSE_ADD_CATEGORY_FORM = "CLOSE_ADD_CATEGORY_FORM";
const OPEN_ADD_IMAGE_FORM = "OPEN_ADD_IMAGE_FORM";
const CLOSE_ADD_IMAGE_FORM = "CLOSE_ADD_IMAGE_FORM";

export {
  OPEN_SIGN_FORM,
  CLOSE_SIGN_FORM,
  OPEN_REGISTER_FORM,
  CLOSE_REGISTER_FORM,
  OPEN_ADD_CATEGORY_FORM,
  CLOSE_ADD_CATEGORY_FORM,
  OPEN_ADD_IMAGE_FORM,
  CLOSE_ADD_IMAGE_FORM,
};
